name = "algo-trading-backend"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[vars]
JWT_SECRET = "wertyukl,mjhgfdszxcvbnm,.jndfgh"
