name = "algo-trading-backend"
main = "index.ts"  
compatibility_date = "2025-07-01"

[vars]
JWT_SECRET = "wertyukl,mjhgfdszxcvbnm,.jndfgh"

[[d1_databases]]
binding = "DB"
database_name = "saral-db"
database_id = "19e3c176-0038-438c-ba63-6af7c672eff4"
